### ISSUE TITLE
non map plots are not showing propery

### ISSUE THREAD

**Issue by aminadibi** [aminadibi/burden_of_COPD#7]
After today's merge, non map plots are not showing properly. 
@ahill187 can you check on your computer? Possibly package version issue? is packrat snapshot updated?

**Comment by ahill187** [comment]
I'll look into it. Is there a SciChat this morning?

**Comment by aminadibi** [comment]
Don’t think so.

**Comment by aminadibi** [comment]
Solved in https://github.com/aminadibi/burden_of_COPD/commit/2dfd9922f43bf7ddeef03818e22ce8ef316b0988
